# Generated by Django 2.0.2 on 2018-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='price',
            new_name='new_price',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='title',
            new_name='new_title',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='new_desc',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='old_description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='old_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
