# Generated by Django 2.0.2 on 2018-10-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181004_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='asin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='old_price',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='asin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asin'),
        ),
    ]
