# Generated by Django 2.0.2 on 2018-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181005_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='new_desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='new_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='desc2',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='desc3',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='desc4',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='desc5',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='desc6',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='desc7',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='desc8',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
