# Generated by Django 2.0.2 on 2018-10-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181005_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='comments',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc1',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc2',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc3',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc4',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc5',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc6',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc7',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='desc8',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
