# Generated by Django 2.0.2 on 2018-10-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181005_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='newProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('bp1', models.CharField(blank=True, max_length=10000, null=True)),
                ('bp2', models.CharField(blank=True, max_length=10000, null=True)),
                ('bp3', models.CharField(blank=True, max_length=10000, null=True)),
                ('bp4', models.CharField(blank=True, max_length=10000, null=True)),
                ('bp5', models.CharField(blank=True, max_length=10000, null=True)),
                ('bp6', models.CharField(blank=True, max_length=10000, null=True)),
                ('bp7', models.CharField(blank=True, max_length=10000, null=True)),
                ('bp8', models.CharField(blank=True, max_length=10000, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('asin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asin')),
            ],
        ),
        migrations.CreateModel(
            name='oldProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('asin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asin')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newProductDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='asin',
        ),
        migrations.DeleteModel(
            name='productDetail',
        ),
    ]
