# Generated by Django 2.0.2 on 2018-10-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181005_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductdetail',
            name='asin',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='oldproductdetail',
            name='asin',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='asin',
        ),
    ]
