# Generated by Django 2.0.2 on 2018-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181007_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldproductdetail',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
