# Generated by Django 2.0.2 on 2018-10-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181007_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldproductdetail',
            old_name='old_title',
            new_name='current_Title',
        ),
        migrations.RenameField(
            model_name='oldproductdetail',
            old_name='title',
            new_name='revised_Title',
        ),
    ]
