# Generated by Django 2.0.2 on 2018-10-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_asin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asin',
            new_name='asinDetail',
        ),
    ]
