# Generated by Django 2.0.2 on 2018-10-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181008_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductdetail',
            name='asin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asinDetail'),
        ),
        migrations.AlterField(
            model_name='oldproductdetail',
            name='asin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asinDetail'),
        ),
    ]
