# Generated by Django 2.0.2 on 2018-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181008_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductdetail',
            name='asin',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='oldproductdetail',
            name='asin',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
