# Generated by Django 2.0.2 on 2018-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181008_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='empDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('asin_done', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('roles', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
