# Generated by Django 2.0.2 on 2018-10-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_asindetail_extracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='oldDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=10000, null=True)),
                ('URL', models.CharField(blank=True, max_length=10000, null=True)),
                ('DESC', models.CharField(blank=True, max_length=100000, null=True)),
                ('BRAND', models.CharField(blank=True, max_length=10000, null=True)),
                ('PRODUCT_DESC', models.CharField(blank=True, max_length=100000, null=True)),
                ('asin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
