# Generated by Django 2.0.2 on 2018-10-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_olddetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olddetail',
            old_name='BRAND',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='DESC',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='NAME',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='PRODUCT_DESC',
            new_name='Product_desc',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='URL',
            new_name='Url',
        ),
    ]
