# Generated by Django 2.0.2 on 2018-10-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181011_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olddetail',
            old_name='Brand',
            new_name='old_brand',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='Desc',
            new_name='old_desc',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='Name',
            new_name='old_name',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='Product_desc',
            new_name='old_product_desc',
        ),
        migrations.RenameField(
            model_name='olddetail',
            old_name='Url',
            new_name='old_url',
        ),
    ]
