# Generated by Django 2.0.2 on 2018-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181011_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddetailamazon',
            name='asin',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
