# Generated by Django 2.0.2 on 2018-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20181011_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddetailamazon',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
