# Generated by Django 2.0.2 on 2018-10-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_olddetailamazon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asindetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='asindetail',
            name='asin',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
