# Generated by Django 2.0.2 on 2018-10-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181017_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='featureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=10000, null=True)),
                ('screen_size_resolution', models.CharField(blank=True, max_length=10000, null=True)),
                ('connectivity_ports', models.CharField(blank=True, max_length=10000, null=True)),
                ('display_and_refresh_rate', models.CharField(blank=True, max_length=10000, null=True)),
                ('sound_output', models.CharField(blank=True, max_length=10000, null=True)),
                ('smart_tv', models.CharField(blank=True, max_length=10000, null=True)),
                ('warranty', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
