# Generated by Django 2.0.2 on 2018-10-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_featureimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductdetail',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
