# Generated by Django 2.0.2 on 2018-10-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20181018_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductdetail',
            name='bp1',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='newproductdetail',
            name='bp2',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='newproductdetail',
            name='bp4',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='newproductdetail',
            name='bp5',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='newproductdetail',
            name='bp6',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='newproductdetail',
            name='bp7',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
